language: ruby
cache: bundler
before_script:
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script:
  - "bundle exec rspec spec"
notifications:
  email: true
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#refinerycms"
  campfire:
    on_success: always
    on_failure: always
    rooms:
      - secure: "JaX+Ckvdd2wqL2bD6t8PHvMDBHxWBlCrkBKPcDKxV0t0DOwzzzwxMryVqcRi\nPsmM/zvmWFATDyRmivhNOpu4lRg9RytSroxZ9nkmbLDqjCyEAZ6tv4yZXME/\nPaxPwmfwgS9g8TKjj3lSWS7rEpqqg0D5S0XIfIHrj6KB6LUmFHc="
env:
  - DB=postgresql
  - DB=mysql
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
